const express = require("express")
const router = express.Router()
const generateNotes = require("../gemini")

router.post("/", async (req, res) => {
  try {
    const { subject, topic, difficulty = "medium" } = req.body

    if (!subject || !topic) {
      return res.status(400).json({ error: "subject and topic are required" })
    }

    const prompt = `
You are a strict teacher.

Generate REAL, exam-ready study notes on "${topic}" in ${subject} at ${difficulty} level.

Rules:
- Be concise but informative
- Avoid generic phrases
- Give practical clarity
- Use proper examples

Return ONLY JSON:
{
  "definition": "...",
  "key_points": ["...", "..."],
  "examples": ["...", "..."],
  "summary": "..."
}
`

    const aiResponse = await generateNotes(prompt)

    let parsed

    try {
      const jsonMatch = aiResponse.match(/\{[\s\S]*\}/)

      if (!jsonMatch) {
        throw new Error("No valid JSON found in AI response")
      }

      parsed = JSON.parse(jsonMatch[0])

    } catch (e) {
      console.error("Parsing error:", aiResponse)
      return res.status(500).json({ error: "Invalid AI response format" })
    }

    if (
      !parsed.definition ||
      !parsed.key_points ||
      !parsed.examples ||
      !parsed.summary
    ) {
      return res.status(500).json({ error: "Incomplete notes generated by AI" })
    }

    res.json({
      success: true,
      data: {
        subject,
        topic,
        difficulty,
        notes: parsed,
        generatedAt: new Date().toISOString()
      }
    })

  } catch (error) {
    console.error("Gemini Error:", error)
    res.status(500).json({ error: "Failed to generate notes" })
  }
})

module.exports = router